#!/bin/sh
clamp() {
  min=$1
  max=$2
  val=$3
  python -c "print(max($min, min($val, $max)))"
}

direction=$1
current=$2
if test "$direction" = "up"
then
  target=$(clamp 1 10 $(($current+1)))
  hyprctl dispatch workspace $target >/dev/null
elif test "$direction" = "down"
then
  target=$(clamp 1 10 $(($current-1)))
  hyprctl dispatch workspace $target >/dev/null
fi
