#!/bin/sh

sinks() {
    wpctl status |
        sed -n '/Sinks:/,/Sources:/p' |
        tr -d '├─│└ ' |
        grep vol |
        grep -v "IEC958" |
        sed 's/\..*//'
}

cycle_sinks() {
    if [ `sinks | grep '*' -A1 | wc -l` -eq 1 ]; then
        wpctl set-default `sinks | sed -n '1p'`
    else
        wpctl set-default `sinks | grep '*' -A1 | sed -n '2p'`
    fi
}

case $1 in
    up)
        wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
        ;;
    down)
        wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
        ;;
    toggle)
        wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
        ;;
    cycle)
        cycle_sinks
        ;;
esac

