#!/bin/sh

echo "KERNEL==\"uinput\", GROUP=\"alice\", MODE=\"0660\", \
  OPTIONS+=\"static_node=uinput\"" | sudo tee \
  /etc/udev/rules.d/80-uinput.rules > /dev/null

sudo su -c 'udevadm control --reload-rules && udevadm trigger'

mkdir -p ~/.config/systemd/user/

cat > ~/.config/systemd/user/ydotoold.service << eof
[Unit]
Description=ydotoold Service

[Service]
ExecStart=/usr/bin/ydotoold

[Install]
WantedBy=default.target
eof

systemctl --user daemon-reload 
systemctl --user enable --now ydotoold.service
