#!/bin/sh

get_vol_status() {
    status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
    vol=$(cut -d' ' -f2 <<< $status)
    muted=$(grep "MUTED" <<< $status)

    echo "{\"volume\": \"$vol\", \"muted\": $([ -n "$muted" ] && echo true || echo false)}"
}

get_vol_status
pactl subscribe | while read -r line; do
    if grep -q "Event 'change' on s" <<< $line; then
        get_vol_status
    fi
done
