background {
    monitor =
    path = screenshot
    blur_passes = 3
}

label {
    monitor =
    text = <span weight="600">$TIME</span>
    font_size = 90
    font_family = NotoSansM Nerd Font
    color = rgb(c2c2c2)

    valign = center
    halign = center
}

input-field {
    monitor =
    size = 64, 64
    outline_thickness = 4

    inner_color = rgba(00000000)
    outer_color = rgba(00000000)

    check_color = rgb(dbbc7f)
    fail_color = rgb(e67e80)

    font_color = rgb(c2c2c2)
    rounding = 99

    placeholder_text =
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>

    position = 0, -160
    halign = center
    valign = center
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = global, 1, 1.5, linear
}
