#!/bin/sh

wmname LG3D &

#  xrandr --auto
xrandr --output HDMI-1 --mode 2560x1440 --rate 144
# multi monitor setup
#  xrandr_args=""
#
#  for monitor in $(bspc query -M --names); do
#      if [[ $monitor == "HDMI"* ]]; then
#          xrandr_args+=" --output $monitor --mode 2560x1440 --rate 144"
#      else
#          xrandr_args+=" --output $monitor --auto"
#      fi
#  done
#
#  xrandr $xrandr_args


bspc monitor -d I II III IV V VI VII # VIII IX X
# bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX
# bspc monitor HDMI-1 -d X


bspc config window_gap          12

bspc config border_width        2
bspc config focused_border_color \#A7C080
bspc config normal_border_color \#2D353B

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc config top_padding 0


bspc rule -a firefox desktop='^1'
bspc rule -a steam desktop='^3'
bspc rule -a notificationtoasts_6_desktop state=floating focus=off
bspc rule -a 'Friends List' state=floating focus=off
bspc rule -a 'Steam - News' state=floating focus=off
bspc rule -a discord desktop='^4' focus=off follow=off
bspc rule -a thunderbird desktop='^4' focus=off follow=off
bspc rule -a Signal desktop='^4' focus=off follow=off
bspc rule -a Spotify desktop='^5'
bspc rule -a Gimp-2.10 desktop='^6'
bspc rule -a Inkscape desktop='^6'
bspc rule -a Arandr state=floating
bspc rule -a Gpick state=floating
bspc rule -a MessageWin state=floating
bspc rule -a "Tor Browser" state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a surf state=floating

~/.fehbg

nm-applet --indicator &
pgrep -x sxhkd > /dev/null || sxhkd &
nvidia-settings --load-config-only &
~/.config/polybar/launch.sh &
/usr/bin/dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom -b &
xsetroot -cursor_name left_ptr &
syncthing -no-browser &
thunderbird &
signal-desktop &
