#!/bin/bash

wmname LG3D &

# monitors script
# change if more than one screen
m=$(bspc query -M --names | head -n1)
m_pc="HDMI*"
if [[ $m == $m_pc ]]; then
    xrandr --output $m --mode 2560x1440 --rate 144
else
    xrandr --output $m --auto
fi

bspc monitor $m -d I II III IV V VI VII # VIII IX X


bspc config window_gap          12
bspc config border_width        2
bspc config focused_border_color \#A7C080
bspc config normal_border_color \#2D353B

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^1'
bspc rule -a steam desktop='^3'
bspc rule -a notificationtoasts_6_desktop state=floating focus=off
bspc rule -a 'Friends List' state=floating focus=off
bspc rule -a 'Steam - News' state=floating focus=off
bspc rule -a discord desktop='^4' focus=off follow=off
bspc rule -a thunderbird desktop='^4' focus=off follow=off
bspc rule -a Signal desktop='^4' focus=off follow=off
bspc rule -a Spotify desktop='^5'
bspc rule -a Gimp-2.10 desktop='^6'
bspc rule -a Inkscape desktop='^6'
bspc rule -a Arandr state=floating
bspc rule -a Gpick state=floating
bspc rule -a MessageWin state=floating
bspc rule -a Pavucontrol state=floating

function open_once() {
    pgrep -x $1 > /dev/null || $* &
}

open_once sxhkd

~/.fehbg &
~/.config/polybar/launch.sh &
/usr/bin/picom -b &
/usr/bin/dunst &
/usr/bin/xsetroot -cursor_name left_ptr &

nm-applet --indicator &
nvidia-settings --load-config-only &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

open_once syncthing -no-browser
open_once signal-desktop
