#!/bin/sh

wmname LG3D &

#  xrandr --auto
xrandr --output HDMI-1 --mode 2560x1440 --rate 144
#  
#  xrandr_args=""
#  
#  for monitor in $(bspc query -M --names); do
#      if [[ $monitor == "HDMI"* ]]; then
#          xrandr_args+=" --output $monitor --mode 2560x1440 --rate 144"
#      else
#          xrandr_args+=" --output $monitor --auto"
#      fi
#  done
#  
#  xrandr $xrandr_args


bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX
# bspc monitor HDMI-1 -d X


bspc config window_gap          0

bspc config border_width         2
bspc config focused_border_color \#c678dd
bspc config normal_border_color \#1f2329

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc config top_padding 0


bspc rule -a firefox desktop='^2'
bspc rule -a steam desktop='^9' focus=off
bspc rule -a 'Friends List' state=floating focus=off
bspc rule -a 'Steam - News' state=floating focus=off
bspc rule -a discord desktop='^10'
bspc rule -a thunderbird desktop='^7'
bspc rule -a Signal desktop='^8' state=floating
bspc rule -a Gimp-2.10 desktop='^5' follow=off focus=off
bspc rule -a Inkscape desktop='^5'
bspc rule -a obsidian desktop='^4'
bspc rule -a code-oss desktop='^3'
bspc rule -a VSCodium desktop='^3'
bspc rule -a Arandr state=floating
bspc rule -a Gpick state=floating
bspc rule -a MessageWin state=floating
bspc rule -a Sxiv state=floating
bspc rule -a "Tor Browser" state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a surf state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a KeePassXC state=floating
bspc rule -a mpv state=floating
bspc rule -a floater state=floating


~/.fehbg

nm-applet --indicator &
pgrep -x sxhkd > /dev/null || sxhkd &
nvidia-settings --load-config-only &
~/.config/polybar/launch.sh &
/usr/bin/dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
picom -b &
xsetroot -cursor_name left_ptr &
flameshot &
syncthing -no-browser &
setxkbmap -layout "pl" -option caps:escape -option shift:both_capslock &
emote &
thunderbird &
signal-desktop &
