return {
    "folke/which-key.nvim",
    config = function()
        require("which-key").setup({
            delay = 1000,
            expand = 1,
            win = {
                padding = { 0, 0, 2, 0 },
                height = { min = 0 },
            },
            layout = {
                width = { min = 0 },
                spacing = 1,
            },
            icons = {
                breadcrumb = "-",
                separator = ":",
                ellipsis = "..",
                mappings = false,
                keys = {
                    Up = "up",
                    Down = "down",
                    Left = "left",
                    Right = "right",
                    C = "c-",
                    M = "m-",
                    S = "s-",
                    CR = "ret",
                    Esc = "esc",
                    NL = "ret",
                    BS = "",
                    Space = "spc",
                    Tab = "tab",
                    F1 = "f1",
                    F2 = "f2",
                    F3 = "f3",
                    F4 = "f4",
                    F5 = "f5",
                    F6 = "f6",
                    F7 = "f7",
                    F8 = "f8",
                    F9 = "f9",
                    F10 = "f10",
                    F11 = "f11",
                    F12 = "f12",
                },
            },
            show_help = false,
        })
    end,
}
