AddPackage 7zip
AddPackage bash-completion
AddPackage bluez
AddPackage bluez-utils
AddPackage brightnessctl
AddPackage fd
AddPackage fzf
AddPackage ghostscript
AddPackage htop
AddPackage imagemagick
AddPackage jq
AddPackage man-db
AddPackage man-pages
AddPackage playerctl
AddPackage ripgrep
AddPackage socat
AddPackage sshfs
AddPackage starship
AddPackage tmux
AddPackage ueberzugpp
AddPackage wiremix
AddPackage yazi
AddPackage zellij
